package DigestionEntity;

import CollectEntity.Message;
import java.util.Arrays;
import java.util.Properties;
import org.apache.kafka.clients.consumer.ConsumerRecord;
import org.apache.kafka.clients.consumer.ConsumerRecords;
import org.apache.kafka.clients.consumer.KafkaConsumer;
import org.apache.kafka.clients.producer.KafkaProducer;
import org.apache.kafka.clients.producer.Producer;
import org.apache.kafka.clients.producer.ProducerRecord;

/**
 *
 * @author José Santos
 * @author Tiago Faria
 */
public class DigestionEntity extends javax.swing.JFrame {

    /**
     * Creates new form DigestionEntity
     */
    public DigestionEntity() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private static boolean isHB(Message message) {
        String[] fields = message.getMessage().split(";");
        if (fields[3].equals("00")) {
            return true;
        }
        return false;
    }

    private static void sendMessage(Message message) {
        //Produce messages to topic EnrichedTopic
        String[] fields = message.getMessage().split(";");

        //All Messages must go to Batch and Report entity
        //Properties for BATCH
        String topicName = "EnrichedTopic1";
        String key = "batchproducer";
        Properties Batchprops = new Properties();
        Batchprops.put("bootstrap.servers", "localhost:9092,localhost:9093,localhost:9094,localhost:9095");
        Batchprops.put("key.serializer", "org.apache.kafka.common.serialization.StringSerializer");
        Batchprops.put("value.serializer", "CollectEntity.MessageSerializer");
        Producer<String, Message> Batchproducer = new KafkaProducer<>(Batchprops);
        ProducerRecord<String, Message> record;

        //Properties for REPORT
        //Properties for ALARM
        switch (fields[3]) {
            case "00":
                Batchprops.put("acks", "0");
                record = new ProducerRecord<>(topicName, key, message);
                Batchproducer.send(record);
                jTextArea1.append("\nSending " + message.getMessage() + "\n");
                break;
            case "01":
                Batchprops.put("acks", "all");
                record = new ProducerRecord<>("EnrichedTopic2", key, message);
                Batchproducer.send(record);
                jTextArea1.append("\nSending " + message.getMessage() + "\n");
                break;
            case "02":
                Batchprops.put("acks", "all");
                record = new ProducerRecord<>(topicName, key, message);
                Batchproducer.send(record);
                jTextArea1.append("\nSending " + message.getMessage() + "\n");
                break;
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DigestionEntity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DigestionEntity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DigestionEntity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DigestionEntity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new DigestionEntity().setVisible(true);

                String topicConsumerName = "EnrichTopic";
                String groupConsumerName = "EnrichTopicGroup";

                //Properties
                Properties propsConsumer = new Properties();
                propsConsumer.put("bootstrap.servers", "localhost:9092,localhost:9093,localhost:9094,localhost:9095");
                propsConsumer.put("group.id", groupConsumerName);
                propsConsumer.put("key.deserializer", "org.apache.kafka.common.serialization.StringDeserializer");
                propsConsumer.put("value.deserializer", "CollectEntity.MessageDeserializer");

                KafkaConsumer<String, Message> consumer = new KafkaConsumer<>(propsConsumer);
                RebalanceListener rebalanceListener = new RebalanceListener(consumer);
                consumer.subscribe(Arrays.asList(topicConsumerName), rebalanceListener);

                //Tudo o que aparece dentro da text área é tratado aqui, inclusive o consumidor para outras coisas.
                Thread thread = new Thread() {
                    public void run() {
                        while (true) {
                            ConsumerRecords<String, Message> records = consumer.poll(100);
                            for (ConsumerRecord<String, Message> record : records) {
                                jTextArea1.append(record.value().getMessage() + "\n");
                                record.value().enrichMessageWithReg();
                                sendMessage(record.value());
                                //commit offsets 
                                if (!isHB(record.value())) {
                                    rebalanceListener.addOffset(record.topic(), record.partition(), record.offset());
                                }
                            }
                        }
                    }
                };
                thread.start();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private static javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
